krita: convert to core22

diff --git a/krita/snapcraft.yaml b/krita/snapcraft.yaml
--- a/krita/snapcraft.yaml
+++ b/krita/snapcraft.yaml
@@ -2,8 +2,9 @@
 name: krita
 grade: stable
 adopt-info: krita
-base: core20
+base: core22
 confinement: strict
+version: 5.1.5
 apps:
     krita:
         common-id: org.kde.krita
@@ -11,17 +12,87 @@ apps:
         extensions:
         - kde-neon
         plugs:
+        - desktop
+        - desktop-legacy
+        - opengl
+        - wayland
+        - x11
         - home
         - network
         - network-bind
-        - removable-media
         - audio-playback
-        environment:
-            QML2_IMPORT_PATH: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qml"
+        - removable-media
+        command-chain:
+        - snap/command-chain/desktop-launch
+assumes:
+- snapd2.43
+compression: lzo
+plugs:
+    desktop:
+        mount-host-font-cache: false
+    icon-themes:
+        interface: content
+        target: $SNAP/data-dir/icons
+        default-provider: gtk-common-themes
+    sound-themes:
+        interface: content
+        target: $SNAP/data-dir/sounds
+        default-provider: gtk-common-themes
+    kf5-5-104-qt-5-15-8-core22:
+        content: kf5-5-104-qt-5-15-8-core22-all
+        interface: content
+        default-provider: kf5-5-104-qt-5-15-8-core22
+        target: $SNAP/kf5
+environment:
+    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
+    QML2_IMPORT_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qml
+hooks:
+    configure:
+        plugs:
+        - desktop
+        command-chain:
+        - snap/command-chain/hooks-configure-desktop
 layout:
-    "/usr/bin/ffmpeg":
-        symlink: "$SNAP/usr/bin/ffmpeg"
+    /usr/bin/ffmpeg:
+        symlink: $SNAP/usr/bin/ffmpeg
+    /usr/share/X11:
+        symlink: $SNAP/kf5/usr/share/X11
+slots:
+    session-dbus-interface:
+        interface: dbus
+        name: org.kde.krita
+        bus: session
+package-repositories:
+-   type: apt
+    components:
+    - main
+    suites:
+    - jammy
+    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
+    url: http://origin.archive.neon.kde.org/user
+    key-server: keyserver.ubuntu.com
 parts:
+    kde-neon:
+        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
+        source-type: local
+        plugin: make
+        make-parameters:
+        - PLATFORM_PLUG=kf5-5-104-qt-5-15-8-core22
+        build-snaps:
+        - kf5-5-104-qt-5-15-8-core22-sdk
+        build-environment:
+        - &id001
+            PATH: /snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/bin${PATH:+:$PATH}
+        - &id002
+            XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
+        - &id003
+            LD_LIBRARY_PATH: /snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/lib/$CRAFT_ARCH_TRIPLET:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib/vala-current:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
+        - &id004
+            PKG_CONFIG_PATH: /snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/lib/pkgconfig:/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
+        - &id005
+            ACLOCAL_PATH: /snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
+        - &id006
+            SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kde-frameworks-5-102-qt-5-15-8-core22-sd/current${SNAPCRAFT_CMAKE_ARGS:+:$SNAPCRAFT_CMAKE_ARGS}
     libheif:
         plugin: autotools
         source: https://github.com/strukturag/libheif.git
@@ -50,12 +121,14 @@ parts:
         source: http://download.kde.org/stable/krita/5.1.5/krita-5.1.5.tar.gz
         plugin: cmake
         cmake-parameters:
-        - "-DCMAKE_INSTALL_PREFIX=/usr"
-        - "-DCMAKE_BUILD_TYPE=Release"
-        - "-DBUILD_TESTING=OFF"
-        - "-DKDE_INSTALL_USE_QT_SYS_PATHS=FALSE"
-        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
+        - -DCMAKE_INSTALL_PREFIX=/usr
+        - -DCMAKE_BUILD_TYPE=Release
+        - -DENABLE_TESTING=OFF
+        - -DBUILD_TESTING=OFF
+        - -DKDE_SKIP_TEST_SETTINGS=ON
+        - -DCMAKE_FIND_ROOT_PATH=/usr\;$CRAFT_STAGE\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current
         build-packages:
+        - cmake
         - libboost-dev
         - libboost-system-dev
         - libeigen3-dev
@@ -78,8 +151,8 @@ parts:
         - vc-dev
         - libmypaint-dev
         - libwebp-dev
-        parse-info:
-        - usr/share/metainfo/org.kde.krita.appdata.xml
+        # parse-info:
+        # - usr/share/metainfo/org.kde.krita.appdata.xml
         stage-packages:
         - freeglut3
         - libboost-system1.71.0
@@ -102,26 +175,36 @@ parts:
         - libslang2
         - webp
         prime:
-        - "-usr/share/fonts/*"
-        - "-usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libQt5*"
-        - "-usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libqt5*"
+        - -usr/lib/*/cmake/*
+        - -usr/include/*
+        - -usr/share/ECM/*
+        - -usr/share/doc/*
+        - -usr/share/man/*
+        - -usr/share/icons/breeze-dark*
+        - -usr/bin/X11
+        - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0
+        - -usr/lib/aspell/*
         override-pull: |
             snapcraftctl pull
-            patch -p1 < $SNAPCRAFT_STAGE/krita_dont_use_native_file_chooser.patch
-    cleanup:
-        after:
-        - krita
-        plugin: nil
-        build-snaps:
-        - kde-frameworks-5-99-qt-5-15-7-core20
-        override-prime: |
-            set -eux
-            for snap in "kde-frameworks-5-100-qt-5-15-7-core20"; do  # List all content-snaps you're using here
-                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
-            done
-            for CRUFT in bug lintian man; do
-                rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
-            done
-            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
-            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
-version: 5.1.5
+            patch -p1 < $CRAFT_STAGE/krita_dont_use_native_file_chooser.patch
+        build-environment: &id007
+        - *id001
+        - *id002
+        - *id003
+        - *id004
+        - *id005
+        - *id006
+    # cleanup:
+    #     after:
+    #     - krita
+    #     plugin: nil
+    #     build-snaps:
+    #     - kde-frameworks-5-99-qt-5-15-7-core20
+    #     override-prime: |
+    #         set -eux
+    #         for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
+    #             cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
+    #         done
+    #         find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
+    #         find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
+
