kdenlive: convert to core22

diff --git a/kdenlive/snapcraft.yaml b/kdenlive/snapcraft.yaml
--- a/kdenlive/snapcraft.yaml
+++ b/kdenlive/snapcraft.yaml
@@ -2,16 +2,21 @@
 name: kdenlive
 confinement: strict
 grade: stable
-base: core20
+base: core22
 adopt-info: kdenlive
 apps:
     kdenlive:
-        extensions:
-        - kde-neon
+        # extensions:
+        # - kde-neon
         common-id: org.kde.kdenlive.desktop
         desktop: usr/share/applications/org.kde.kdenlive.desktop
         command: usr/bin/kdenlive
         plugs:
+        - desktop
+        - desktop-legacy
+        - opengl
+        - wayland
+        - x11
         - home
         - network
         - network-bind
@@ -19,23 +24,54 @@ apps:
         - audio-record
         - removable-media
         - system-observe
+        command-chain:
+        - snap/command-chain/desktop-launch
     pip:
         command: bin/pip
         plugs:
         - network
         - home
+assumes:
+- snapd2.43
+compression: lzo
+plugs:
+    desktop:
+        mount-host-font-cache: false
+    icon-themes:
+        interface: content
+        target: $SNAP/data-dir/icons
+        default-provider: gtk-common-themes
+    sound-themes:
+        interface: content
+        target: $SNAP/data-dir/sounds
+        default-provider: gtk-common-themes
+    kf5-5-104-qt-5-15-8-core22:
+        content: kf5-5-104-qt-5-15-8-core22-all
+        interface: content
+        default-provider: kf5-5-104-qt-5-15-8-core22
+        target: $SNAP/kf5
+hooks:
+    configure:
+        plugs:
+        - desktop
+        command-chain:
+        - snap/command-chain/hooks-configure-desktop
+layout:
+    /usr/share/X11:
+        symlink: $SNAP/kf5/usr/share/X11
 environment:
     PYTHONPYCACHEPREFIX: "$SNAP_USER_COMMON/.pycache"
     PYTHONUSERBASE: "$SNAP_USER_COMMON/.local"
     PIP_USER: 1
     PYTHONPATH: "$PYTHONUSERBASE/lib/python3.8/site-packages:$SNAP/lib/python3.8/site-packages:$SNAP/usr/lib/python3/dist-packages"
-    MLT_REPOSITORY: "$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/mlt-7/"
+    MLT_REPOSITORY: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET/mlt-7/"
     MLT_DATA: "$SNAP/usr/share/mlt-7/"
     MLT_ROOT_DIR: "$SNAP/usr/"
     LADSPA_PATH: "$SNAP/usr/lib/ladspa"
     FREI0R_PATH: "$SNAP/usr/lib/frei0r-1"
     MLT_PROFILES_PATH: "$SNAP/usr/share/mlt-7/profiles/"
     MLT_PRESETS_PATH: "$SNAP/usr/share/mlt-7/presets/"
+    SNAP_DESKTOP_RUNTIME: $SNAP/kf5
 slots:
     session-dbus-interface:
         interface: dbus
@@ -46,24 +82,53 @@ package-repositories:
     components:
     - main
     suites:
-    - focal
+    - jammy
     key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
     url: http://origin.archive.neon.kde.org/user
     key-server: keyserver.ubuntu.com
 parts:
+    kde-neon:
+        source: /snap/snapcraft/current/share/snapcraft/extensions/desktop/kde-neon
+        source-type: local
+        plugin: make
+        make-parameters:
+        - PLATFORM_PLUG=kf5-5-104-qt-5-15-8-core22
+        build-snaps:
+        - kf5-5-104-qt-5-15-8-core22-sdk
+        build-environment:
+        - &id001
+            PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/bin${PATH:+:$PATH}
+        - &id002
+            XDG_DATA_DIRS: $SNAPCRAFT_STAGE/usr/share:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share:/usr/share${XDG_DATA_DIRS:+:$XDG_DATA_DIRS}
+        - &id003
+            LD_LIBRARY_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/vala-current:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pulseaudio${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
+        - &id004
+            PKG_CONFIG_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/lib/pkgconfig:/snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
+        - &id005
+            ACLOCAL_PATH: /snap/kf5-5-104-qt-5-15-8-core22-sdk/current/usr/share/aclocal${ACLOCAL_PATH:+:$ACLOCAL_PATH}
+        - &id006
+            SNAPCRAFT_CMAKE_ARGS: -DCMAKE_FIND_ROOT_PATH=/snap/kf5-5-104-qt-5-15-8-core22-sdk/current${SNAPCRAFT_CMAKE_ARGS:+:$SNAPCRAFT_CMAKE_ARGS}
     python-deps:
+        after:
+        - kde-neon
         plugin: python
+        source: .
         python-packages:
+        - python
         - vosk
         - srt
         - pip
         stage:
         - "-pyvenv.cfg"
     glaxnimate:
+        after:
+        - kde-neon
+        - python-deps
         plugin: cmake
         source: https://gitlab.com/mattbas/glaxnimate.git
         source-tag: 0.5.1
         build-packages:
+        - cmake
         - qt5-image-formats-plugins
         - qttools5-dev
         - libpython3-dev
@@ -78,14 +143,24 @@ parts:
         cmake-parameters:
         - "-DCMAKE_INSTALL_PREFIX=/usr"
         - "-DCMAKE_BUILD_TYPE=Release"
-        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
+        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
         - "-DBUILD_TESTING=OFF"
+        build-environment: &id007
+        - *id001
+        - *id002
+        - *id003
+        - *id004
+        - *id005
+        - *id006
     mlt:
         after:
+        - kde-neon
+        - python-deps
         - glaxnimate
         plugin: cmake
         source: https://github.com/mltframework/mlt/releases/download/v7.8.0/mlt-7.8.0.tar.gz
         build-packages:
+        - cmake
         - libxml2-dev
         - libavformat-dev
         - libmovit-dev
@@ -101,10 +176,12 @@ parts:
         - "-DCMAKE_INSTALL_PREFIX=/usr"
         - "-DCMAKE_BUILD_TYPE=Release"
         - "-DMOD_GLAXNIMATE=ON"
-        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
+        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
         - "-DBUILD_TESTING=OFF"
+        build-environment: *id007
     kdenlive:
         after:
+        - kde-neon
         - python-deps
         - glaxnimate
         - mlt
@@ -112,12 +189,13 @@ parts:
         - usr/share/metainfo/org.kde.kdenlive.appdata.xml
         plugin: cmake
         build-packages:
+        - cmake
         - libkf5doctools-dev
         - libkf5purpose-dev
         - librttr-dev
         - libv4l-dev
         stage-packages:
-        -   on amd64:
+        - on amd64:
             - libpsm-infinipath1
         - ffmpeg
         - frei0r-plugins
@@ -132,38 +210,49 @@ parts:
         - kio-extras
         - mediainfo
         - libqt5networkauth5
-        source: http://download.kde.org/stable/release-service/22.12.2/src/kdenlive-22.12.2.tar.xz
+        source: http://download.kde.org/stable/release-service/22.12.3/src/kdenlive-22.12.3.tar.xz
         cmake-parameters:
         - "-DCMAKE_INSTALL_PREFIX=/usr"
         - "-DCMAKE_BUILD_TYPE=Release"
         - "-DMOD_GLAXNIMATE=ON"
-        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$SNAPCRAFT_STAGE\\;/snap/kde-frameworks-5-99-qt-5-15-7-core20-sdk/current"
+        - "-DCMAKE_FIND_ROOT_PATH=/usr\\;$CRAFT_STAGE\\;/snap/kf5-5-104-qt-5-15-8-core22-sdk/current"
         - "-DBUILD_TESTING=OFF"
+        build-environment: *id007
         override-build: |
             snapcraftctl build
-            sed -i "${SNAPCRAFT_PART_INSTALL}/usr/share/applications/org.kde.kdenlive.desktop" -e 's|Icon=kdenlive$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/kdenlive.svg|'
-            cd "${SNAPCRAFT_PART_INSTALL}/usr/share/icons/hicolor/scalable/apps"
+            sed -i "${CRAFT_PART_INSTALL}/usr/share/applications/org.kde.kdenlive.desktop" -e 's|Icon=kdenlive$|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/kdenlive.svg|'
+            cd "${CRAFT_PART_INSTALL}/usr/share/icons/hicolor/scalable/apps"
             gzip -d -c kdenlive.svgz > kdenlive.svg
-            if [ "$SNAPCRAFT_TARGET_ARCH" = amd64 ]; then
-                ln -sf ../libpsm1/libpsm_infinipath.so.1.16  $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpsm_infinipath.so.1
+            if [ "$CRAFT_TARGET_ARCH" = amd64 ]; then
+                ln -sf ../libpsm1/libpsm_infinipath.so.1.16  $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/libpsm_infinipath.so.1
             fi
-    cleanup:
-        after:
-        - kdenlive
-        - python-deps
-        - glaxnimate
-        - mlt
-        plugin: nil
-        build-snaps:
-        - kde-frameworks-5-99-qt-5-15-7-core20
-        override-prime: |
-            set -eux
-            for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
-                cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
-            done
-            for CRUFT in bug lintian man; do
-                rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
-            done
-            find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
-            find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
-version: 22.12.2
+        prime:
+        - -usr/lib/*/cmake/*
+        - -usr/include/*
+        - -usr/share/ECM/*
+        - -usr/share/doc/*
+        - -usr/share/man/*
+        - -usr/share/icons/breeze-dark*
+        - -usr/bin/X11
+        - -usr/lib/gcc/$CRAFT_ARCH_TRIPLET/6.0.0
+        - -usr/lib/aspell/*
+    # cleanup:
+    #     after:
+    #     - kdenlive
+    #     - python-deps
+    #     - glaxnimate
+    #     - mlt
+    #     plugin: nil
+    #     build-snaps:
+    #     - kde-frameworks-5-99-qt-5-15-7-core20
+    #     override-prime: |
+    #         set -eux
+    #         for snap in "kde-frameworks-5-99-qt-5-15-7-core20"; do  # List all content-snaps you're using here
+    #             cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
+    #         done
+    #         for CRUFT in bug lintian man; do
+    #             rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
+    #         done
+    #         find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
+    #         find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
+version: 22.12.3
